//#region "Security"
//// USERS MODULE
export const CREATE_USER_PERMISSION_ID = 1;
export const MODIFY_ACCESS_PASSWORD_ID = 2;
export const DISABLE_USER_PERMISSION_ID = 3;
export const UPDATE_USER_PROFILE_ID = 89;

//// ROLES MODULE
export const CREATE_ROLE_PERMISSION_ID = 4;
export const ASSIGN_ROLE_PERMISSION_ID = 5;
export const UPDATE_ROLE_PERMISSION_ID = 90;

//// GENERAL MASTERS MODULE
export const MANAGE_MASTER_PERMISSION_ID = 7;
export const CREATE_ROLE_MASTER_PERMISSION_ID = 11;

//// TASKS MODULE
export const MANAGE_TASK_PERMISSION_ID = 6;

//// MILESTONES MODULE
export const MANAGE_MILESTONES_PERMISSION_ID = 10;

//#endregion

//#region "General Masters"

//// COUNTRIES MODULE
export const CHECK_COUNTRY_PERMISSION_ID = 8;
export const UPDATE_COUNTRY_PERMISSION_ID = 9;

//// PROVINCE MODULE
export const CHECK_STATE_PERMISSION_ID = 12;
export const UPDATE_STATE_PERMISSION_ID = 13;

//// COMPANIES MODULE
export const CHECK_COMPANIES_PERMISSION_ID = 14;
export const UPDATE_COMPANIES_PERMISSION_ID = 34;

//// CITIES MODULE
export const CHECK_CITIES_PERMISSION_ID = 15;
export const UPDATE_CITIES_PERMISSION_ID = 35;

//// CURRENCY MODULE
export const CHECK_CURRENCY_PERMISSION_ID = 16;
export const UPDATE_CURRENCY_PERMISSION_ID = 36;

//// DISTRICT MODULE
export const CHECK_DISTRICT_PERMISSION_ID = 17;
export const UPDATE_DISTRICT_PERMISSION_ID = 37;

//// BRAND MODULE
export const CHECK_BRAND_PERMISSION_ID = 19;
export const UPDATE_BRAND_PERMISSION_ID = 39;

//// PORT MODULE
export const CHECK_PORT_PERMISSION_ID = 18;
export const UPDATE_PORT_PERMISSION_ID = 38;

//// DIVICE TYPES MODULE
export const CHECK_DIVICE_TYPES_PERMISSION_ID = 20;
export const UPDATE_DIVICE_TYPES_PERMISSION_ID = 40;

//// DIVICES MODULE
export const CHECK_DIVICES_PERMISSION_ID = 21;
export const UPDATE_DIVICES_PERMISSION_ID = 41;

//// BANKS MODULE
export const CHECK_BANKS_PERMISSION_ID = 22;
export const UPDATE_BANKS_PERMISSION_ID = 42;

//// SUBSIDIARIES MODULE
export const CHECK_SUBSIDIARIES_PERMISSION_ID = 23;
export const UPDATE_SUBSIDIARIES_PERMISSION_ID = 43;

//// AREAS MODULE
export const CHECK_AREAS_PERMISSION_ID = 24;
export const UPDATE_AREAS_PERMISSION_ID = 44;

//// TAXES MODULE
export const CHECK_TAXES_PERMISSION_ID = 25;
export const UPDATE_TAXES_PERMISSION_ID = 45;

//// TAX RATES MODULE
export const CHECK_TAX_RATES_PERMISSION_ID = 26;
export const UPDATE_TAX_RATES_PERMISSION_ID = 46;

//// MOTIVES TYPES MODULE
export const CHECK_MOTIVES_TYPES_PERMISSION_ID = 27;
export const UPDATE_MOTIVES_TYPES_PERMISSION_ID = 47;

//// MOTIVES MODULE
export const CHECK_MOTIVES_PERMISSION_ID = 28;
export const UPDATE_MOTIVES_PERMISSION_ID = 48;

//// PRICE GROUPING MODULE
export const CHECK_PRICE_GROUPING_PERMISSION_ID = 29;
export const UPDATE_PRICE_GROUPING_PERMISSION_ID = 49;

//// PRICE TYPES MODULE
export const CHECK_PRICE_TYPES_PERMISSION_ID = 30;
export const UPDATE_PRICE_TYPES_PERMISSION_ID = 50;

//// TAXE TYPE APPLICATION MODULE
export const CHECK_TAXE_TYPE_APPLICATION_PERMISSION_ID = 31;
export const UPDATE_TAXE_TYPE_APPLICATION_PERMISSION_ID = 51;

//// PAYMENT METHODS MODULE
export const CHECK_PAYMENT_METHODS_PERMISSION_ID = 32;
export const UPDATE_PAYMENT_METHODS_PERMISSION_ID = 52;

//// DOCUMENT TYPES MODULE
export const CHECK_DOCUMENT_TYPES_PERMISSION_ID = 33;
export const UPDATE_DOCUMENT_TYPES_PERMISSION_ID = 53;

//// BRANCH OFFICE MODULE
export const CHECK_BRANCH_OFFICES_PERMISSION_ID = 23;
export const UPDATE_BRANCH_OFFICES_PERMISSION_ID = 43;

//#endregion

//#region "MPC"
export const MANAGE_MPC_PERMISSION_ID = 54;

//// MEASURE GROUPING MODULE
export const CHECK_MEASURE_GROUPING_PERMISSION_ID = 55;
export const UPDATE_MEASURE_GROUPING_PERMISSION_ID = 56;

//// MEASUREMENT UNITS MODULE
export const CHECK_MEASUREMENT_UNITS_PERMISSION_ID = 57;
export const UPDATE_MEASUREMENT_UNITS_PERMISSION_ID = 58;

//// ATTRIBUTES GROUPING MODULE
export const CHECK_ATTRIBUTES_GROUPING_PERMISSION_ID = 59;
export const UPDATE_ATTRIBUTES_GROUPING_PERMISSION_ID = 60;

//// ATTRIBUTES MODULE
export const CHECK_ATTRIBUTES_PERMISSION_ID = 61;
export const UPDATE_ATTRIBUTES_PERMISSION_ID = 62;

//// ATTRIBUTE OPTIONS MODULE
export const CHECK_ATTRIBUTE_OPTIONS_PERMISSION_ID = 63;
export const UPDATE_ATTRIBUTE_OPTIONS_PERMISSION_ID = 64;

//// PACKAGING PRESENTATION MODULE
export const CHECK_PACKAGING_PRESENTATION_PERMISSION_ID = 65;
export const UPDATE_PACKAGING_PRESENTATION_PERMISSION_ID = 94;

//// PACKAGING USES MODULE
export const CHECK_PACKAGING_USES_PERMISSION_ID = 66;
export const UPDATE_PACKAGING_USES_PERMISSION_ID = 95;

//// GTIN TYPE MODULE
export const CHECK_GTIN_TYPE_PERMISSION_ID = 67;
export const UPDATE_GTIN_TYPE_PERMISSION_ID = 68;

//// MULTIMEDIA USES MODULE
export const CHECK_MULTIMEDIA_USES_PERMISSION_ID = 69;
export const UPDATE_MULTIMEDIA_USES_PERMISSION_ID = 70;

//// PRODUCT ASSOCIATIONS MODULE
export const CHECK_PRODUCT_ASSOCIATIONS_PERMISSION_ID = 71;
export const UPDATE_PRODUCT_ASSOCIATIONS_PERMISSION_ID = 72;

//// CLASSIFICATIONS MODULE
export const CHECK_CLASSIFICATIONS_PERMISSION_ID = 73;
export const UPDATE_CLASSIFICATIONS_PERMISSION_ID = 74;

//// PRODUCT CATEGORIES MODULE
export const CHECK_PRODUCT_CATEGORIES_PERMISSION_ID = 75;
export const UPDATE_PRODUCT_CATEGORIES_PERMISSION_ID = 76;
export const CHANGE_LEVEL_CATEGORIES_PERMISSION_ID = 116;

//// VALIDATION RANGES MODULE
export const CHECK_VALIDATION_RANGES_PERMISSION_ID = 77;
export const UPDATE_VALIDATION_RANGES_PERMISSION_ID = 78;

////  SOURCE TYPES MODULE
export const CHECK_SOURCE_TYPES_PERMISSION_ID = 79;
export const UPDATE_SOURCE_TYPES_PERMISSION_ID = 80;

//// DESCRIPTION TYPES MODULE
export const CHECK_DESCRIPTION_TYPES_PERMISSION_ID = 81;
export const UPDATE_DESCRIPTION_TYPES_PERMISSION_ID = 82;

//// DECREASE TYPES MODULE
export const CHECK_DECREASE_TYPES_PERMISSION_ID = 83;
export const UPDATE_DECREASE_TYPES_PERMISSION_ID = 84;

//// TYPE OF PRODUCTS TYPES MODULES
export const CHECK_TYPE_PRODUCT_PARTS_PERMISSION_ID = 85;
export const UPDATE_TYPE_PRODUCT_PARTS_PERMISSION_ID = 86;


//// INSERT TYPE MODULES
export const CHECK_INSERT_TYPE_PERMISSION_ID = 96;
export const UPDATE_INSERT_TYPE_PERMISSION_ID = 97;

//// PRODUCT CATALOG
export const CHECK_PRODUCT_CATALOG_PERMISSION_ID = 107;
export const CHECK_PRODUCT_PERMISSION_ID = 109;
export const MANAGE_GENERAL_SECTION_PERMISSION_ID = 110;
export const MANAGE_COMPLEMENTARY_SECTION_PERMISSION_ID = 111;
export const MANAGE_PUBLICATIONS_SECTION_PERMISSION_ID = 112;
export const MANAGE_QUALITY_CONTROL_SECTION_PERMISSION_ID = 113;
export const UPDATE_FINISH_PRODUCT_PERMISSION_ID = 114;
export const UPDATE_CANCEL_PRODUCT_PERMISSION_ID = 115;
export const UPDATE_PRODUCT_PERMISSION_ID = 108;

//#endregion "Mpc Masters"

//#region "IMS"
export const CHECK_GROUPING_INVENTORY_REASON_PERMISSION_ID = 103;
export const UPDATE_INSERT_GROUPING_INVENTORY_REASON_PERMISSION_ID = 104;

export const CHECK_INVENTORY_REASON_PERMISSION_ID = 105;
export const UPDATE_INVENTORY_REASON_PERMISSION_ID = 106;
//#endregion

//#region "Mpc Producto"

// export const CHECK_PRODUCT_PUBLICATION=0;
// export const UPDATE_PRODUCT_PUBLICATION=0;

//#endregion "Mpc Producto